
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace FieldTale.DataTables
{
public partial class Tables
{
    public TbItem TbItem {get; }
    public TbScene TbScene {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbItem = new TbItem(loader("Item/tbitem"));
        TbScene = new TbScene(loader("Scene/tbscene"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbScene.ResolveRef(this);
    }
}

}

